//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 17:41:52  on 19 March 2001
//
//	Generated for file: D:\wordfind\src\score.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"ScoreBoard"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1100
#define EditFormForm                              1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1010, Default Button ID = 0)
#define EditFormDoneButton                        1101	//(Left Origin = 34, Top Origin = 127, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EditFormCancelButton                      1102	//(Left Origin = 97, Top Origin = 128, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EditFormNameField                         1105	//(Left Origin = 50, Top Origin = 30, Width = 100, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 1, Has Scroll Bar = 0, Numeric = 0)
#define EditFormScoreField                        1106	//(Left Origin = 50, Top Origin = 80, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define EditFormNameLabel                         1103	//(Left Origin = 18, Top Origin = 30, Usable = 1, Font = Bold)
#define EditFormScoreLabel                        1104	//(Left Origin = 19, Top Origin = 80, Usable = 1, Font = Bold)


//	Resource: tFRM 1000
#define ScoreFormForm                             1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define ScoreFormNewButton                        1002	//(Left Origin = 5, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ScoreFormEditButton                       1003	//(Left Origin = 59, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ScoreFormDeleteButton                     1004	//(Left Origin = 119, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ScoreFormSortOrderLabel                   1006	//(Left Origin = 5, Top Origin = 132, Usable = 1, Font = Standard)
#define ScoreFormScoreList                        1001	//(Left Origin = 1, Top Origin = 17, Width = 158, Usable = 1, Font = Standard, Visible Items = 10)
#define ScoreFormSortOrderList                    1007	//(Left Origin = 40, Top Origin = 132, Width = 40, Usable = 0, Font = Standard, Visible Items = 2)
#define ScoreFormSortOrderPopTrigger              1005	//(Left Origin = 50, Top Origin = 132, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1007)


//	Resource: Talt 1000
#define AboutAlert                                1000
#define AboutOK                                   0

//	Resource: MBAR 1010
#define EditFormMenuMenuBar                       1010

//	Resource: MBAR 1000
#define ScoreFormMenuMenuBar                      1000

//	Resource: MENU 1200
#define EditMenu                                  1200
#define EditUndo                                  1200	//  Command Key: U
#define EditCut                                   1201	//  Command Key: X
#define EditCopy                                  1202	//  Command Key: C
#define EditPaste                                 1203	//  Command Key: P
#define EditSelectAll                             1204	//  Command Key: S
#define EditKeyboard                              1206	//  Command Key: K
#define EditGraffiti                              1207	//  Command Key: G

//	Resource: MENU 1100
#define HelpMenu                                  1100
#define HelpAbout                                 1100	//  Command Key: A
