//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 11:32:49 PM on Thursday, July 15, 1999
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"PalmWord"
//
//	Pilot App Version: 		"1.0"



//	Resource: tFRM 1000
#define ClientFormForm                            1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ClientFormGoButtonButton                  1003	//(Left Origin = 58, Top Origin = 80, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ClientFormPatternFieldField               1001	//(Left Origin = 13, Top Origin = 48, Width = 137, Height = 14, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ClientFormUnnamed1002Label                1002	//(Left Origin = 8, Top Origin = 23, Usable = 1, Font = Standard)


//	Resource: tFRM 1100
#define WordFormForm                              1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define WordFormNextButtonButton                  1102	//(Left Origin = 13, Top Origin = 139, Width = 63, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WordFormNewButtonButton                   1103	//(Left Origin = 91, Top Origin = 140, Width = 57, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WordFormWordListList                      1101	//(Left Origin = 5, Top Origin = 4, Width = 150, Usable = 1, Font = Standard, Visible Items = 8)

