//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 1:21:58 AM on Tuesday, March 09, 2004
//
//	Generated for file: C:\Documents and Settings\gram\My Documents\My Palm Projects\wordfind\rsc\wordfindlite.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"WordFindLite"
//
//	Palm App Version:		"2.9"


//	Resource: tFRM 1100
#define WordFormForm                              1100
#define WordFormNextButton                        1102
#define WordFormNewButton                         1103
#define WordFormRestartButton                     1104
#define WordFormStopButton                        1106
#define WordFormDebugField                        1105
#define WordFormWordsList                         1107

//	Resource: tFRM 1000
#define MainFormForm                              1000
#define MainFormTemplateClearButton               1003
#define MainFormAnagramClearButton                1004
#define MainFormLetterAButton                     1007
#define MainFormLetterBButton                     1008
#define MainFormLetterCButton                     1009
#define MainFormLetterDButton                     1010
#define MainFormLetterEButton                     1011
#define MainFormLetterFButton                     1012
#define MainFormLetterGButton                     1013
#define MainFormLetterHButton                     1014
#define MainFormLetterIButton                     1015
#define MainFormLetterJButton                     1016
#define MainFormLetterKButton                     1017
#define MainFormLetterLButton                     1018
#define MainFormLetterMButton                     1019
#define MainFormLetterNButton                     1020
#define MainFormLetterOButton                     1021
#define MainFormLetterPButton                     1022
#define MainFormLetterQButton                     1023
#define MainFormLetterRButton                     1024
#define MainFormLetterSButton                     1025
#define MainFormLetterTButton                     1026
#define MainFormLetterUButton                     1027
#define MainFormLetterVButton                     1028
#define MainFormLetterWButton                     1029
#define MainFormLetterXButton                     1030
#define MainFormLetterYButton                     1031
#define MainFormLetterZButton                     1032
#define MainFormBreak1Button                      1033
#define MainFormWild1Button                       1034
#define MainFormGoButton                          1035
#define MainFormBreak2Button                      1036
#define MainFormBackspaceButton                   1038
#define MainFormTemplateField                     1005
#define MainFormAnagramField                      1006
#define MainFormTemplateLabel                     1001
#define MainFormAnagramLabel                      1002


//	Resource: Talt 1000
#define AboutAlert                                1000
#define AboutOK                                   0

//	Resource: Talt 1100
#define ErrorAlert                                1100
#define ErrorOK                                   0


//	Resource: MBAR 1000
#define MainMenuBar                               1000


//	Resource: MENU 1100
#define HelpMenu                                  1100
#define HelpAboutWordFindLite                     1100

//	Resource: MENU 1000
#define EditMenu                                  1000
#define EditUndo                                  1000
#define EditCut                                   1001
#define EditCopy                                  1002
#define EditPaste                                 1003
#define EditSelectAll                             1004
#define EditKeyboard                              1006
#define EditGraffiti                              1007


//	Resource: tSTR 1000
#define HelpString                                1000

