//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 9:49:38 PM on Thursday, March 07, 2002
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"WordFind++"
//
//	Palm App Version: 		"2.7"



//	Resource: tFRM 1000
#define MainFormForm                              1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1060, Default Button ID = 0)
#define MainFormGoButton                          1003	//(Left Origin = 139, Top Origin = 23, Width = 20, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormClearButton                       1015	//(Left Origin = 59, Top Origin = 23, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormCaseButton                        1016	//(Left Origin = 100, Top Origin = 147, Width = 59, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormWildButton                        1017	//(Left Origin = 67, Top Origin = 147, Width = 28, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormLeftBracketButton                 1018	//(Left Origin = 1, Top Origin = 147, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormRightBracketButton                1019	//(Left Origin = 17, Top Origin = 147, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormVowelButton                       1020	//(Left Origin = 50, Top Origin = 131, Width = 45, Height = 12, Usable = 1, Anchor Left = 0, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormConsonantButton                   1021	//(Left Origin = 100, Top Origin = 131, Width = 59, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormNegateButton                      1022	//(Left Origin = 50, Top Origin = 147, Width = 12, Height = 12, Usable = 1, Anchor Left = 0, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormRangeButton                       1025	//(Left Origin = 33, Top Origin = 147, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormBreakButton                       1026	//(Left Origin = 1, Top Origin = 131, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormSpaceButton                       1027	//(Left Origin = 17, Top Origin = 131, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormSlashButton                       1028	//(Left Origin = 33, Top Origin = 131, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainFormPatPromptButton                   1031	//(Left Origin = 5, Top Origin = 23, Width = 50, Height = 12, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 0, Font = Bold)
#define MainFormMultiCheckbox                     1011	//(Left Origin = 90, Top Origin = 80, Width = 68, Height = 11, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainFormPatternField                      1001	//(Left Origin = 8, Top Origin = 42, Width = 139, Height = 40, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 63, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainFormUnnamed1005Label                  1005	//(Left Origin = 5, Top Origin = 80, Usable = 1, Font = Bold)
#define MainFormWordLengthsLabel                  1006	//(Left Origin = 5, Top Origin = 97, Usable = 1, Font = Bold)
#define MainFormWordCountsLabel                   1007	//(Left Origin = 5, Top Origin = 114, Usable = 1, Font = Bold)
#define MainFormWLToLabel                         1013	//(Left Origin = 110, Top Origin = 97, Usable = 1, Font = Bold)
#define MainFormWCToLabel                         1014	//(Left Origin = 110, Top Origin = 114, Usable = 1, Font = Bold)
#define MainFormHistoryList                       1024	//(Left Origin = 1, Top Origin = 20, Width = 157, Usable = 0, Font = Standard, Visible Items = 11)
#define MainFormHistoryPopTrigger                 1023	//(Left Origin = 89, Top Origin = 24, Width = 35, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1024)
#define MainFormMinLengthSelTrigger               1004	//(Left Origin = 80, Top Origin = 97, Width = 35, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard)
#define MainFormMaxLengthSelTrigger               1008	//(Left Origin = 125, Top Origin = 97, Width = 35, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard)
#define MainFormMinCountSelTrigger                1009	//(Left Origin = 80, Top Origin = 114, Width = 35, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard)
#define MainFormMatchTypeSelTrigger               1010	//(Left Origin = 45, Top Origin = 80, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard)
#define MainFormMaxCountSelTrigger                1012	//(Left Origin = 125, Top Origin = 114, Width = 35, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard)
#define WordFindFormGroupID                       0


//	Resource: tFRM 1100
#define WordFormForm                              1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define WordFormNextButton                        1102	//(Left Origin = 1, Top Origin = 147, Width = 38, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WordFormNewButton                         1103	//(Left Origin = 81, Top Origin = 147, Width = 38, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WordFormRestartButton                     1104	//(Left Origin = 41, Top Origin = 147, Width = 38, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WordFormStopButton                        1106	//(Left Origin = 121, Top Origin = 147, Width = 38, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WordFormDebugField                        1105	//(Left Origin = 3, Top Origin = 128, Width = 153, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define WordFormWordsList                         1107	//(Left Origin = 1, Top Origin = 18, Width = 150, Usable = 1, Font = Standard, Visible Items = 11)


//	Resource: tFRM 1200
#define MatchTypeForm                             1200	//(Left Origin = 1, Top Origin = 39, Width = 158, Height = 118, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1220, Menu Bar ID = 0, Default Button ID = 1205)
#define MatchTypeMatchTypeOKButton                1205	//(Left Origin = 50, Top Origin = 90, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MatchTypeNormalCheckbox                   1201	//(Left Origin = 20, Top Origin = 25, Width = 100, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define MatchTypePrefixCheckbox                   1202	//(Left Origin = 20, Top Origin = 45, Width = 100, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define MatchTypeSuffixCheckbox                   1203	//(Left Origin = 20, Top Origin = 65, Width = 100, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define MatchTypeFormGroupID                      1


//	Resource: tFRM 1300
#define WordLengthForm                            1300	//(Left Origin = 1, Top Origin = 29, Width = 158, Height = 128, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1320, Menu Bar ID = 0, Default Button ID = 1320)
#define WordLengthLengthOKButton                  1320	//(Left Origin = 54, Top Origin = 108, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WordLengthNoLengthLimitCheckbox           1301	//(Left Origin = 10, Top Origin = 20, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1302Checkbox             1302	//(Left Origin = 10, Top Origin = 30, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1303Checkbox             1303	//(Left Origin = 10, Top Origin = 40, Width = 55, Height = 12, Usable = 1, Selected = 0, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1304Checkbox             1304	//(Left Origin = 10, Top Origin = 50, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1305Checkbox             1305	//(Left Origin = 10, Top Origin = 60, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1306Checkbox             1306	//(Left Origin = 10, Top Origin = 70, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1307Checkbox             1307	//(Left Origin = 10, Top Origin = 80, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1308Checkbox             1308	//(Left Origin = 11, Top Origin = 91, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1309Checkbox             1309	//(Left Origin = 80, Top Origin = 20, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1310Checkbox             1310	//(Left Origin = 80, Top Origin = 30, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1311Checkbox             1311	//(Left Origin = 80, Top Origin = 40, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1312Checkbox             1312	//(Left Origin = 80, Top Origin = 50, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1313Checkbox             1313	//(Left Origin = 80, Top Origin = 60, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1314Checkbox             1314	//(Left Origin = 80, Top Origin = 70, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordLengthUnnamed1315Checkbox             1315	//(Left Origin = 80, Top Origin = 80, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define WordLengthUnnamed1316Checkbox             1316	//(Left Origin = 80, Top Origin = 90, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define WordLengthLimitsFormGroupID               1
#define WordLengthLimitsFormGroupID2              0


//	Resource: tFRM 1400
#define WordCountForm                             1400	//(Left Origin = 1, Top Origin = 29, Width = 158, Height = 128, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1420, Menu Bar ID = 0, Default Button ID = 1403)
#define WordCountCountLimitOKButton               1416	//(Left Origin = 50, Top Origin = 99, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WordCountNoCountLimitCheckbox             1401	//(Left Origin = 10, Top Origin = 20, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1402Checkbox              1402	//(Left Origin = 10, Top Origin = 30, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1403Checkbox              1403	//(Left Origin = 10, Top Origin = 40, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1404Checkbox              1404	//(Left Origin = 10, Top Origin = 50, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1405Checkbox              1405	//(Left Origin = 10, Top Origin = 60, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1406Checkbox              1406	//(Left Origin = 10, Top Origin = 70, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1407Checkbox              1407	//(Left Origin = 10, Top Origin = 80, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1408Checkbox              1408	//(Left Origin = 80, Top Origin = 20, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1409Checkbox              1409	//(Left Origin = 80, Top Origin = 30, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1410Checkbox              1410	//(Left Origin = 80, Top Origin = 40, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1411Checkbox              1411	//(Left Origin = 80, Top Origin = 50, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1412Checkbox              1412	//(Left Origin = 80, Top Origin = 60, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1413Checkbox              1413	//(Left Origin = 80, Top Origin = 70, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountUnnamed1414Checkbox              1414	//(Left Origin = 80, Top Origin = 80, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 1, Font = Standard)
#define WordCountLimitsFormGroupID                1


//	Resource: tFRM 1700
#define DictFormForm                              1700	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define DictFormDeleteButton                      1702	//(Left Origin = 22, Top Origin = 145, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DictFormCancelButton                      1703	//(Left Origin = 97, Top Origin = 145, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DictFormDictionariesList                  1701	//(Left Origin = 0, Top Origin = 18, Width = 160, Usable = 1, Font = Standard, Visible Items = 11)


//	Resource: tFRM 1500
#define GlobFormForm                              1500	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1060, Default Button ID = 0)
#define GlobFormNegateButton                      1501	//(Left Origin = 50, Top Origin = 147, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GlobFormRangeButton                       1502	//(Left Origin = 33, Top Origin = 147, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GlobFormRightBracketButton                1503	//(Left Origin = 17, Top Origin = 147, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GlobFormLeftBracketButton                 1504	//(Left Origin = 1, Top Origin = 147, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GlobFormWildButton                        1505	//(Left Origin = 1, Top Origin = 131, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GlobFormAnyButton                         1506	//(Left Origin = 17, Top Origin = 131, Width = 29, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GlobFormVowelButton                       1507	//(Left Origin = 50, Top Origin = 131, Width = 52, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GlobFormConsonantButton                   1508	//(Left Origin = 107, Top Origin = 131, Width = 52, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GlobFormGlobPromptButton                  1510	//(Left Origin = 5, Top Origin = 23, Width = 50, Height = 12, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 0, Font = Bold)
#define GlobFormClearButton                       1511	//(Left Origin = 59, Top Origin = 23, Width = 25, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GlobFormGoButton                          1513	//(Left Origin = 139, Top Origin = 23, Width = 20, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GlobFormPatternField                      1509	//(Left Origin = 8, Top Origin = 40, Width = 139, Height = 28, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 63, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GlobFormHistoryList                       1514	//(Left Origin = 1, Top Origin = 20, Width = 157, Usable = 0, Font = Standard, Visible Items = 11)
#define GlobFormHistoryPopTrigger                 1512	//(Left Origin = 89, Top Origin = 24, Width = 35, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1514)


//	Resource: Talt 1100
#define ErrorAlert                                1100
#define ErrorOK                                   0

//	Resource: Talt 1000
#define AboutBoxAlert                             1000
#define AboutBoxOK                                0

//	Resource: MBAR 1060
#define MainMenuBar                               1060

//	Resource: MENU 1100
#define EditMenu                                  1100
#define EditDeleteDictionary                      1100
#define EditUndo                                  1102	//  Command Key: U
#define EditCut                                   1103	//  Command Key: X
#define EditCopy                                  1104	//  Command Key: C
#define EditPaste                                 1105	//  Command Key: P
#define EditSelectAll                             1106	//  Command Key: S
#define EditKeyboard                              1108	//  Command Key: K
#define EditGraffiti                              1109	//  Command Key: G

//	Resource: MENU 1000
#define HelpMenu                                  1000
#define HelpAboutWordFind                         1000	//  Command Key: A

//	Resource: tSTR 1420
#define WordCountHelpString                       1420	// "For multi-word searches, the word count limits let you restrict to matches consisting of a specified number of words (or range of number of words). Selecting Default causes a sensible default to be used. "

//	Resource: tSTR 1320
#define LengthLimitHelpString                     1320	// "The length limits let you control the length of words  when using prefix or suffix, and/or multi-word matching.  Selecting Default means that a sensible default should  be used.  "

//	Resource: tSTR 1220
#define MatchTypeHelpString                       1220	// "Normal (Use All) matching uses all the letters in the pattern, an  is what you should use for single word crossword clues and anagrams.  Prefix matching is useful to find words "

//	Resource: tSTR 1085
#define MainHelpString                            1085	// "Welcome to WordFind++, the ideal"

//	Resource: tSTR 10180
#define CreatedforHelpIDString                    10180	// "You need to load a dictionary database before you can do lookups! "
